---
title: "Option, Result, Enums, and Contract Methods"
date: 2024-04-29
tags: ["sway", "rust", "viem"]
---

## What I Learned

### Rust

**types**

`Option` type is used when a value may or may not be present. It takes one of two values: `Some(T)` when an element of type `T` is available, and `None` when no element is present.

```rust
fn find_age(name: &str) -> Option<u32> {
    let ages = [("Alice", 30), ("Bob", 24)];
    for &(n, age) in ages.iter() {
        if n == name {
            return Some(age);
        }
    }
    None
}

let age = find_age("Alice");
match age {
    Some(a) => println!("Alice is {} years old.", a),
    None => println!("Age not found."),
}

```

`is_some()` and `is_none()` checks if an `Option` element has is a `Some` or `None` value respectively.

`Result` type is used in operations that can fail. It is defined as `Result<T, E>`. `Ok<T>` being successful and carrying type `T` and `Err(E)` being an error carrying the error type `E`.

```rust
fn divide(numerator: f64, denominator: f64) -> Result<f64, String> {
    if denominator == 0.0 {
        Err("Cannot divide by zero.".to_string())
    } else {
        Ok(numerator / denominator)
    }
}

match divide(10.0, 0.0) {
    Ok(result) => println!("The result is {}", result),
    Err(e) => println!("Error: {}", e),
}
```

**enum for custom error types**

```rust
enum ValidationError {
    InvalidInput,
}
```

To provide meaningful error messages and to comply with traits like std::error::Error, it's good practice to implement the Display trait for the error enum.

```rust
use std::fmt;

impl fmt::Display for ValidationError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ValidationError::InvalidInput => write!(f, "Input is invalid"),
        }
    }
}
```

Use this error enum in a function that validates a simple condition (e.g., checking if a number is positive) and returns a Result.

```rust
fn validate_number(num: i32) -> Result<i32, ValidationError> {
    if num <= 0 {
        Err(ValidationError::InvalidInput)
    } else {
        Ok(num)
    }
}
```

Using this function and custom error type.

```rust
fn main() {
    let result = validate_number(-10);

    match result {
        Ok(num) => println!("Validated number: {}", num),
        Err(e) => println!("Error: {}", e),
    }
}
```

### Sway

**converting int sizes**

```sway
use std::{primitive_conversions::{u32::*, u64::*,},};

// Going from smaller to larger
let u32_from_u16: u32 = u16_1.as_u32();
// Going from larger to smaller. Might be `None` type if it overflows
let u32_from_u64_1: Option<u32> = u64_1.try_as_u32();
```

### Viem

deployContract
waitForTransactionReceipt
readContract

```ts
const hash = await client.deployContract({ abi, bytecode: `0x${bin}` });

/**
 * The video's example uses `getTransactionReceipt` but that was not
 * waiting for the deploy contract transaction to process.
 */
const { contractAddress } = await client.waitForTransactionReceipt({ hash });

if (contractAddress) {
  const x = await client.readContract({
    address: contractAddress,
    abi,
    functionName: "x",
  });

  console.log(x); // The value of the contract's storage variable 'x' = 125
}
```

Can use the `getContract` function to create a contract instance

```ts
const contract = getContract({
  client,
  address: contractAddress,
  abi: funJsonts.contracts["contracts/Fun.sol:Fun"].abi,
});

// Now we can use it like this
const x = await contract.read.x();
// Instead of this
const x = await client.readContract({
  address: contractAddress,
  abi,
  functionName: "x",
});
```

## Challenges and Questions

In Rust, all arms of a `match` statement must return the same type, so you can't use `match` to run operations on success/error that return different types.

```rust
let result = process_data("some input"); // Result type

if result.is_ok() {
    println!("The operation was successful.");
}

let value = process_data("some input").unwrap(); // Be cautious: this will panic if `result` is `Err`

let value = process_data("empty input").unwrap_or(0); // Returns 0 if `result` is `Err`

let value = process_data("some input").expect("Failed to process data"); // Similar to unwrap(), but allows you to specify a custom panic message:

if let Ok(value) = process_data("some input") {
    println!("Received value: {}", value);
} else {
    println!("Failed to process data.");
}

```

## Additional Resources

[type conversions](https://docs.fuel.network/docs/nightly/sway/basics/converting_types/)

[Viem Speed Run](https://www.youtube.com/watch?v=P9oUqVsHBkA)
